### ISSUE TITLE
Why is this package called "wired-fonts" instead of "weird-fonts"?

### ISSUE THREAD

**Issue by Raka-loah** [beizhedenglong/weird-fonts#1]
Last time I checked, npm has no package named "weird-fonts". This accidental (or intended) typo is triggering my OCD and makes me feel so 𝓦𝓮𝓲𝓻𝓭.

**Comment by shuiRong** [comment]
I think it's a typo :p  @beizhedenglong

**Comment by beizhedenglong** [comment]
I created this toy package is just for fun. A "wired"  name makes more fun.
To be honest, it's a typo🌚.
